### ISSUE TITLE
Add benchmarks with 'hashable' and 'blake2b'

### ISSUE THREAD

**Issue by chshersh** [plaprade/murmur3#6]
It's good to have performance comparison with other hashing libraries because `murmur` is supposed to be the fastest one.

**Comment by jprupp** [comment]
This code is not meant to be particularly efficient. It's purpose is to support Bloom filters in Haskoin Core. It is possible that we'll remove Bloom filter support entirely in favor of querying block chain indices such as Haskoin Store. We Haskoin Developers do not plan to spend any significant effort on this library.

If you are shopping for a high-performance non-cryptographic hash function, I recommend you go for one written in a lower-level programming language with good Haskell bindings instead of using this one.

Now, if you provide benchmark results as a pull request, I'll include them in the readme file.
